### ISSUE TITLE
Question about forking from your code for my own personal site

### ISSUE THREAD

**Issue by CameronPodd** [alipianu/alipianu.github.io#43]
Hi Alex, I'm Cameron Podd, a junior at USC in Los Angeles.  I am currently looking to build out a personal career hub (website, automatic resume building, etc) and came across yours, and honestly, I love it.  You've made a great site here, and to be honest, I'm a terrible designer (my strength lies in backend).  I was wondering if I could fork your repository as a starting place to build my own site.  I am, of course, happy to note in the code and on the site, and you are of course welcome to any additions or changes I may make.  

I've forked it and done a little experimentation, but before I do any more (and especially before I make it public) I'd like to get your permission - I don't want to step on your toes even if it is open source.  

Let me know.  You've made a great site, and I'd love to work from it.  Feel free to contact me on this issue, or directly at podd@usc.edu.  Thanks in advance!

**Comment by alipianu** [comment]
Of course Cameron, you can fork it and do with it whatever you wish. If you have any questions about the code or need any help with the frontend I'd be happy to help. I appreciate the acknowledgement and I'm glad you like it.

My future plans are to add custom analytic tracking components and API endpoints to track all user interaction on the site. Unfortunately Google Analytics doesn't track time well with SPA's. I'll add you as a contributor to the new repo when I get around to it, might come in handy for your site and your help/input would be greatly appreciated.

**Comment by CameronPodd** [comment]
Thanks, Alex.  I really appreciate it.  I have forked it and will continue to work on it.  Those sound like great plans.  I will be sure to reach out if I have any questions or help.  As it is, you've documented it quite well.  I'll let you know when it goes live, but if you'd ever like to take a look, feel free to pull my fork!

**Comment by alipianu** [comment]
Great, I'll definitely take a look when it's done. Looking forward to it!
